---
- import_playbook: ../playbook.yml

- hosts: aml2
  tasks:
  - name: Clear caches for package box
    shell: |
      export HISTSIZE=0
      yum clean all
      sudo rm -rf /var/cache/yum
      sudo dd if=/dev/zero of=/ZERO bs=1M
      sudo rm -f /ZERO
