---
- name: Install nginx1.12 from amazon-linux-extras
  command: amazon-linux-extras install nginx1.12 -y
  become: yes
  args:
    creates: /usr/sbin/nginx

- name: create nginx paths
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  become: yes
  with_items:
    - sites-available
    - sites-enabled

- name: Copy conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes

- include: code_path.yml
- include: pid_bug.yml

- name: Change lib nginx ownership to ec2-user
  file:
    path: /var/lib/nginx
    owner: ec2-user
    group: ec2-user
    recurse: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
