---
- name: Make nginx.service.d
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
  become: yes

- name: Make override.conf on nginx.service.d
  file:
    path: /etc/systemd/system/nginx.service.d/override.conf
    state: touch
  become: yes

- name: Print fix bug data
  lineinfile:
    path: /etc/systemd/system/nginx.service.d/override.conf
    line: '[Service]\nExecStartPost=/bin/sleep 0.1'
  become: yes

- name: Reload the daemon
  command: systemctl daemon-reload
  become: yes
