---
- src: vandcarlos.php_aml2
- src: vandcarlos.nginx_aml2
- src: vandcarlos.node_aml2
- src: vandcarlos.repos_aml2
- src: geerlingguy.composer
- src: geerlingguy.redis
- src: geerlingguy.git
- src: oktapodia.phpunit
- src: ocha.yarn
