---
- name: Download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /home/ec2-user/composer-installer.php
    checksum: sha384:93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8

- name: Generate composer.phar
  command: php /home/ec2-user/composer-installer.php
  args:
    creates: /usr/local/bin/composer

- name: Move composer.phar to /usr/bin
  command: mv /home/ec2-user/composer.phar /usr/local/bin/composer
  become: yes
  args:
    creates: /usr/local/bin/composer

- name: Create symlink
  file:
    src: /usr/local/bin/composer
    dest: /usr/bin/composer
    state: link
    force: yes
  become: yes
